/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author godna
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        Cargando = new javax.swing.JLabel();
        VetSoft = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        BackGroundImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(98, 182, 203));
        BackGround.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/Assets/LogoVetSoft4X.png"))); // NOI18N
        BackGround.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 260, 250));

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/Assets/Linea.png"))); // NOI18N
        Linea.setText("jLabel2");
        BackGround.add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 440, 60));
        BackGround.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 920, 10));

        Cargando.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Cargando.setText("Cargando...");
        BackGround.add(Cargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        VetSoft.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        VetSoft.setText("VetSoft+");
        BackGround.add(VetSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 210, 70));

        LoadingValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        LoadingValue.setText("0%");
        BackGround.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 30, -1));

        BackGroundImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/Assets/VetSoft ¡ (900 × 500 px).png"))); // NOI18N
        BackGround.add(BackGroundImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);

         try{
              for(int i = 0;i<=100;i++){
                  Thread.sleep(100);
                  sp.LoadingValue.setText(i + "%");
                  
                  if(i==10){
                      sp.Cargando.setText("Iniciando Programa...");
                  }
                  if(i== 30){
                      sp.Cargando.setText("Conectando base de datos...");
                  }
                  if(i== 50){
                      sp.Cargando.setText("Recopilando datos...");
                  }
                  if(i== 70){
                      sp.Cargando.setText("Cargando...");
                  }
                  if(i == 90){
                      sp.Cargando.setText("Iniciando Programa.");
                  }
                  sp.LoadingBar.setValue(i);
                  
              }
         }catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
    
}
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel BackGroundImagen;
    private javax.swing.JLabel Cargando;
    private javax.swing.JLabel Linea;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel VetSoft;
    // End of variables declaration//GEN-END:variables
}
