/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AVista.Clientes;

import AControlador.ctCliente;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author godna
 */
public class Cliente extends javax.swing.JPanel {

    
    private String nombre;

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    private boolean selected;

    public Cliente(String nombre) throws SQLException {
        this.nombre=nombre;
        initComponents();
        setData();
        setOpaque(false);
    }

    public void setData() throws SQLException {

        try {
        
                txtNom.setText(nombre);

           // }
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }

    @Override
    public void paint(Graphics graphics) {
        Graphics2D g2 = (Graphics2D) graphics.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(242, 242, 242));
        if (selected) {
            g2.setColor(new Color(94, 156, 255));
            //g2.drawRoundRect(0,0,getWidth(),, WIDTH, WIDTH, HEIGHT, WIDTH, HEIGHT);
        }
        g2.dispose();
        super.paint(graphics);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox2 = new Design.PictureBox();
        pic = new Design.PictureBox();
        txtNom = new javax.swing.JLabel();

        setBackground(new Color(255,255,255,0));
        setForeground(new Color(255,255,255,0));

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/AVista/Clientes/Cliente5.png"))); // NOI18N

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/AVista/Clientes/ClienteI.png"))); // NOI18N
        pictureBox2.add(pic);
        pic.setBounds(40, 40, 70, 90);

        txtNom.setText("Nombre");
        pictureBox2.add(txtNom);
        txtNom.setBounds(190, 70, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.PictureBox pic;
    private Design.PictureBox pictureBox2;
    private javax.swing.JLabel txtNom;
    // End of variables declaration//GEN-END:variables
}
