/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AVista.Clientes;

import AModelo.mdClientes;
import AControlador.ctCliente;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author godna
 */
public class FormCliente extends javax.swing.JPanel {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }
    
    ctCliente cI = new ctCliente();
    
    public final void DataCliente(){
        
    this.setEvent(new EventCard() {
        @Override
        public void cardClick(Component com, ModelCard card) {
            setSelected(com);
            showItem(card);
        }
    });
    int id=1;
    try{
//Ocupa ResultSet para traer los datos de la base
    ResultSet rs = ccar.CargarCartas();
//Declaras que el bucle dure hasta que ya no haya más datos en la tabla
    while(rs.next()){
//para agregar la imagen de la base a la carta
    ImageIcon pro = new ImageIcon(rs.getBytes("Foto"));
    Image image = pro.getImage();
    Image scaledImage = image.getScaledInstance(171, 125, Image.SCALE_SMOOTH); // Ajusta los valores de anchoDeseado y altoDeseado
//   
 ImageIcon scaledIcon = new ImageIcon(scaledImage);
//addItem se llama el método.
//para la foto agrega el icono que se le dio una imagen de la base de datos llamamos el objeto //resultset y le damos los objetos que almaceno según el nombre de la sentencia que se le dio
addItem(new ModelCard(id++, rs.getString("Nombre"), rs.getDouble("Precio"), scaledIcon, rs.getString("Estado"), rs.getString("Categoria"), rs.getString("Descripcion")));
    }
    }catch(Exception ex){
    JOptionPane.showMessageDialog(null, "Error: " + ex, "ERROR", JOptionPane.PLAIN_MESSAGE);
    }
    }
//Habilitar eventos de la carta
private EventCard event;

    public void setEvent(EventCard event) {
        this.event = event;
    }
//Metodo para agregar la carta
public void addItem(ModelCard data){
//Clase para el componente
    Card card = new Card();
    card.setData(data);
    card.setSize(350,144);
    card.addMouseListener(new MouseAdapter() {
//Metodo cuando se de click en la carta
        @Override
        public void mousePressed(MouseEvent mc){
        if(SwingUtilities.isLeftMouseButton(mc)){
            event.cardClick(card, data);
        }
        }
    });
    PanelProductos.add(card);
    PanelProductos.repaint();
    PanelProductos.revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelCliente1 = new Design.PanelCliente();

        setOpaque(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(panelCliente1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private Design.PanelCliente panelCliente1;
    // End of variables declaration//GEN-END:variables
}
